name: Copy lib files to demo folders of landing page website

on:
  push:
    paths:
      - 'dist/*'

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up SSH key
        env:
          SSH_KEY: ${{ secrets.DO_SSH_KEY }}
        run: |
          echo "$SSH_KEY" > ssh_key
          chmod 600 ssh_key

      - name: Copy to demo show-hide
        env:
          REMOTE_HOST: ${{ secrets.DO_HOST }}
          REMOTE_USER: ${{ secrets.DO_USER }}
          REMOTE_PATH: '/var/www/jssprout.com/demos/show-hide/lib'
          SOURCE_PATH: 'dist/*'
        run: |
          scp -i ssh_key -o StrictHostKeyChecking=no -tt -r $SOURCE_PATH $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH

     
